### ISSUE TITLE
AWS Managed Microsoft AD support

### ISSUE THREAD

**Issue by Type1J** [hashicorp/terraform-provider-ad#89] opened 2021-03-17 02:29 UTC
### Description

AWS doesn't seem to use WinRM to configure its Managed ADs, but I would really like to use this plugin with them. Please add whatever is nessisary to make that happen!

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by aareet** [comment] 2021-03-17 03:00
I believe this is a duplicate of #40?

**Closed** 2021-03-17 03:00 UTC
Labels: enhancement
